dsad

diff --git a/srcs/wordpress/dockerfile b/srcs/wordpress/dockerfile
--- a/srcs/wordpress/dockerfile
+++ b/srcs/wordpress/dockerfile
@@ -1,45 +1,85 @@
-FROM alpine:3.7
+FROM php:7.4-fpm-alpine
 
-LABEL APP "wordpress"
+# persistent dependencies
+RUN apk add --no-cache \
+# in theory, docker-entrypoint.sh is POSIX-compliant, but priority is a working, consistent image
+		bash \
+# BusyBox sed is not sufficient for some of our sed expressions
+		sed \
+# Ghostscript is required for rendering PDF previews
+		ghostscript
 
-ENV TIMEZONE Europe/Paris
-ENV VERSION_WORDPRESS 4.9.6
-ENV APACHE_SERVER_NAME example.com
-ENV APACHE_SERVER_PATH /var/www/localhost/htdocs
-ENV MYSQL_DATABASE app
-ENV MYSQL_USER app
-ENV MYSQL_PASSWORD app
-ENV MYSQL_HOST mysql
+# install the PHP extensions we need (https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions)
+RUN set -ex; \
+	\
+	apk add --no-cache --virtual .build-deps \
+		$PHPIZE_DEPS \
+		freetype-dev \
+		imagemagick-dev \
+		libjpeg-turbo-dev \
+		libpng-dev \
+		libzip-dev \
+	; \
+	\
+	docker-php-ext-configure gd --with-freetype --with-jpeg; \
+	docker-php-ext-install -j "$(nproc)" \
+		bcmath \
+		exif \
+		gd \
+		mysqli \
+		opcache \
+		zip \
+	; \
+	pecl install imagick-3.4.4; \
+	docker-php-ext-enable imagick; \
+	\
+	runDeps="$( \
+		scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
+			| tr ',' '\n' \
+			| sort -u \
+			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
+	)"; \
+	apk add --virtual .wordpress-phpexts-rundeps $runDeps; \
+	apk del .build-deps
 
-# Installing dependencies
-RUN apk add --no-cache --virtual .build-deps unzip
-RUN apk add --no-cache apache2 php7 php7-apache2 php7-openssl php7-xml php7-pdo php7-mcrypt php7-session php7-mysqli php7-zlib su-exec
-RUN mkdir -p /run/apache2 /run/httpd
+# set recommended PHP.ini settings
+# see https://secure.php.net/manual/en/opcache.installation.php
+RUN { \
+		echo 'opcache.memory_consumption=128'; \
+		echo 'opcache.interned_strings_buffer=8'; \
+		echo 'opcache.max_accelerated_files=4000'; \
+		echo 'opcache.revalidate_freq=2'; \
+		echo 'opcache.fast_shutdown=1'; \
+	} > /usr/local/etc/php/conf.d/opcache-recommended.ini
+# https://wordpress.org/support/article/editing-wp-config-php/#configure-error-logging
+RUN { \
+# https://www.php.net/manual/en/errorfunc.constants.php
+# https://github.com/docker-library/wordpress/issues/420#issuecomment-517839670
+		echo 'error_reporting = E_ERROR | E_WARNING | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_RECOVERABLE_ERROR'; \
+		echo 'display_errors = Off'; \
+		echo 'display_startup_errors = Off'; \
+		echo 'log_errors = On'; \
+		echo 'error_log = /dev/stderr'; \
+		echo 'log_errors_max_len = 1024'; \
+		echo 'ignore_repeated_errors = On'; \
+		echo 'ignore_repeated_source = Off'; \
+		echo 'html_errors = Off'; \
+	} > /usr/local/etc/php/conf.d/error-logging.ini
 
-# Work path
-WORKDIR /scripts
+VOLUME /var/www/html
 
-# Download & install wordpress
-ADD https://wordpress.org/wordpress-${VERSION_WORDPRESS}.zip ./
-RUN unzip -q wordpress-${VERSION_WORDPRESS}.zip -d ./ && \
-        rm -rf ${APACHE_SERVER_PATH} && \
-        mv wordpress/ ${APACHE_SERVER_PATH} && \
-        rm /scripts/wordpress-${VERSION_WORDPRESS}.zip \
-            ${APACHE_SERVER_PATH}/wp-config-sample.php \
-            ${APACHE_SERVER_PATH}/license.txt \
-            ${APACHE_SERVER_PATH}/readme.html && \
-        chown -R apache:apache ${APACHE_SERVER_PATH} && \
-        apk del .build-deps
+ENV WORDPRESS_VERSION 5.3.2
+ENV WORDPRESS_SHA1 fded476f112dbab14e3b5acddd2bcfa550e7b01b
 
-# Copy of the HTTPD startup script
+RUN set -ex; \
+	curl -o wordpress.tar.gz -fSL "https://wordpress.org/wordpress-${WORDPRESS_VERSION}.tar.gz"; \
+	echo "$WORDPRESS_SHA1 *wordpress.tar.gz" | sha1sum -c -; \
+# upstream tarballs include ./wordpress/ so this gives us /usr/src/wordpress
+	tar -xzf wordpress.tar.gz -C /usr/src/; \
+	rm wordpress.tar.gz; \
+	chown -R www-data:www-data /usr/src/wordpress
 
-COPY ./scripts/start.sh ./start.sh
-#RUN chmod +x /scripts/start.sh
-RUN chmod +x start.sh
-COPY ./files/wp-config.php ${APACHE_SERVER_PATH}/wp-config.php
+COPY docker-entrypoint.sh /usr/local/bin/
 
-EXPOSE 80
-#EXPOSE 5050
-
-
-ENTRYPOINT [ "./start.sh" ]
+ENTRYPOINT ["docker-entrypoint.sh"]
+CMD ["php-fpm"]
